namespace Omp.Core;

/// <summary>
/// Represents a transcript item containing a response generated by an AI assistant, including the resulting text, reasoning process, and model execution metadata.
/// </summary>
public sealed class AssistantItem : TranscriptItem
{
    /// <summary>
    /// Gets or sets the text.
    /// </summary>
    public string Text { get; set; } = "";

    /// <summary>
    /// Gets or sets the thinking.
    /// </summary>
    public string Thinking { get; set; } = "";

    /// <summary>
    /// Gets or sets a value indicating whether streaming.
    /// </summary>
    public bool Streaming { get; set; }

    /// <summary>
    /// Gets or sets the model.
    /// </summary>
    public string? Model { get; set; }

    /// <summary>
    /// Gets or sets the stop reason.
    /// </summary>
    public string? StopReason { get; set; }

    /// <summary>
    /// Gets or sets the error message.
    /// </summary>
    public string? ErrorMessage { get; set; }

    /// <summary>
    /// Gets or sets the usage.
    /// </summary>
    public UsageView? Usage { get; set; }
}
