namespace Omp.Core;

/// <summary>
/// Represents a transcript item containing the text output generated by a command.
/// </summary>
public sealed class CommandOutputItem : TranscriptItem
{
    /// <summary>
    /// Gets or sets the text.
    /// </summary>
    public string Text { get; set; } = "";
}
