using System.Collections.Generic;
using System.Linq;
using System.Text;
using OhMyPi.VisualStudio.UI.Model;

namespace OhMyPi.VisualStudio.UI.Tests
{
    public class MarkdownTests
    {
        /// <summary>HTML-like rendering of the parsed blocks so expectations read like the HTML a Markdown renderer would emit.</summary>
        private static string Render(string markdown) => string.Concat(Markdown.Parse(markdown).Select(Block));

        private static string Block(MdBlock block)
        {
            switch (block)
            {
                case MdParagraph p:
                    return "<p>" + string.Join("<br>", p.Lines.Select(Inlines)) + "</p>";
                case MdHeading h:
                    return $"<h{h.Level}>{Inlines(h.Inlines)}</h{h.Level}>";
                case MdCodeBlock c:
                    return $"<pre{(c.Language == null ? "" : $" lang=\"{c.Language}\"")}>{c.Code}</pre>";
                case MdList l:
                    return List(l);
                case MdTable t:
                    var sb = new StringBuilder("<table><tr>");
                    for (var i = 0; i < t.Header.Count; i++) sb.Append(Cell("th", t.Header[i], t.Aligns, i));
                    sb.Append("</tr>");
                    foreach (var row in t.Rows)
                    {
                        sb.Append("<tr>");
                        for (var i = 0; i < row.Count; i++) sb.Append(Cell("td", row[i], t.Aligns, i));
                        sb.Append("</tr>");
                    }
                    return sb.Append("</table>").ToString();
                default:
                    return "?";
            }
        }

        private static string Cell(string tag, IReadOnlyList<MdInline> inlines, IReadOnlyList<MdAlign> aligns, int index)
        {
            var align = index < aligns.Count && aligns[index] != MdAlign.Left ? $" align=\"{aligns[index].ToString().ToLowerInvariant()}\"" : "";
            return $"<{tag}{align}>{Inlines(inlines)}</{tag}>";
        }

        private static string List(MdList list)
        {
            var tag = list.Ordered ? "ol" : "ul";
            var start = list.Ordered && list.Start != 1 ? $" start=\"{list.Start}\"" : "";
            return $"<{tag}{start}>" + string.Concat(list.Items.Select(i => "<li>" + Inlines(i.Inlines) + string.Concat(i.Children.Select(List)) + "</li>")) + $"</{tag}>";
        }

        private static string Inlines(IReadOnlyList<MdInline> inlines) => string.Concat(inlines.Select(i =>
        {
            switch (i.Kind)
            {
                case MdInlineKind.Code: return $"<code>{i.Text}</code>";
                case MdInlineKind.Bold: return $"<strong>{(i.Children.Count > 0 ? Inlines(i.Children) : i.Text)}</strong>";
                case MdInlineKind.Italic: return $"<em>{(i.Children.Count > 0 ? Inlines(i.Children) : i.Text)}</em>";
                case MdInlineKind.Link: return $"<a {i.Url}>{i.Text}</a>";
                default: return i.Text;
            }
        }));

        [Fact]
        public void Bold_and_italic_can_hold_inline_code()
        {
            Assert.Equal("<p><strong>Skrypt <code>scripts/a.ps1</code></strong> (69 KB)</p>", Render("**Skrypt `scripts/a.ps1`** (69 KB)"));
            Assert.Equal("<p><strong>F-0-2 (P3): <code><auto-generated</code> wykrywane w całym pliku</strong></p>", Render("**F-0-2 (P3): `<auto-generated` wykrywane w całym pliku**"));
            Assert.Equal("<p><em>see <code>x</code> here</em></p>", Render("*see `x` here*"));
            Assert.Equal("<p><code>a**b**c</code> and <strong>bold</strong></p>", Render("`a**b**c` and **bold**"));
        }

        [Fact]
        public void Raw_html_stays_literal_text()
        {
            Assert.Equal("<p>hi <img src=x onerror=\"alert(1)\"> & <script>bad()</script></p>", Render("hi <img src=x onerror=\"alert(1)\"> & <script>bad()</script>"));
        }

        [Fact]
        public void Non_ascii_digit_markers_are_text_not_list_items()
        {
            Assert.Equal("<p>１. 項目</p>", Render("１. 項目"));
            Assert.Equal("<p>١. بند</p>", Render("١. بند"));
        }

        [Fact]
        public void A_long_line_of_brackets_parses_in_linear_time()
        {
            var line = new string('[', 40_000);
            var watch = System.Diagnostics.Stopwatch.StartNew();
            Assert.Equal("<p>" + line + "</p>", Render(line));
            Assert.True(watch.ElapsedMilliseconds < 500, $"took {watch.ElapsedMilliseconds} ms");
            Assert.Equal("<p>[a <a u>b</a></p>", Render("[a [b](u)"));
        }

        [Fact]
        public void Code_fences_keep_content_and_language()
        {
            Assert.Equal("<p>before</p><pre lang=\"ts\">const a = 1 < 2;</pre><p>after</p>", Render("before\n```ts\nconst a = 1 < 2;\n```\nafter"));
        }

        [Fact]
        public void Unterminated_fence_while_streaming_is_code()
        {
            Assert.Equal("<pre>partial <b></pre>", Render("```\npartial <b>"));
        }

        [Fact]
        public void Inline_code_bold_and_italic()
        {
            Assert.Equal("<p>use <code>a<b</code> and <strong>strong</strong> and <em>soft</em> text</p>", Render("use `a<b` and **strong** and *soft* text"));
            Assert.Equal("<p><em>under</em> snake_case_name 2 * 3 * 4</p>", Render("_under_ snake_case_name 2 * 3 * 4"));
        }

        [Fact]
        public void Links_carry_their_target()
        {
            Assert.Equal("<p>see <a https://x.dev/docs>docs</a></p>", Render("see [docs](https://x.dev/docs)"));
        }

        [Fact]
        public void Markdown_inside_inline_code_is_not_interpreted()
        {
            Assert.Equal("<p><code>**x**</code></p>", Render("`**x**`"));
        }

        [Fact]
        public void Bullet_lists_with_inline_formatting()
        {
            Assert.Equal("<ul><li>a <b></li><li><strong>b</strong></li></ul>", Render("- a <b>\n* **b**"));
        }

        [Fact]
        public void Ordered_lists_keep_non_one_start()
        {
            Assert.Equal("<ol><li>one</li><li>two</li></ol>", Render("1. one\n2. two"));
            Assert.Equal("<ol start=\"3\"><li>three</li></ol>", Render("3) three"));
        }

        [Fact]
        public void Nested_items_and_continuation_lines()
        {
            Assert.Equal("<ul><li>a<ul><li>b more</li></ul></li><li>c</li></ul>", Render("- a\n  - b\n    more\n- c"));
        }

        [Fact]
        public void Paragraph_ends_before_list_and_restarts_after()
        {
            Assert.Equal("<p>Intro:</p><ul><li>a</li></ul><p>after</p>", Render("Intro:\n- a\n\nafter"));
        }

        [Fact]
        public void Dash_without_space_is_not_a_list()
        {
            Assert.Equal("<p>-not a list</p>", Render("-not a list"));
        }

        [Fact]
        public void Pipe_tables_with_alignment()
        {
            Assert.Equal("<table><tr><th>A</th><th align=\"right\">B</th></tr><tr><td><code>x</code></td><td align=\"right\">2</td></tr></table>", Render("| A | B |\n| --- | ---: |\n| `x` | 2 |"));
        }

        [Fact]
        public void Pipe_line_without_separator_is_prose()
        {
            Assert.Equal("<p>| a | b |</p>", Render("| a | b |"));
        }

        [Fact]
        public void Headings_are_blocks_outside_paragraphs()
        {
            Assert.Equal("<p>intro</p><h3>Title</h3><h4>Sub <code>x</code></h4><h6>Deep</h6><p>text</p>", Render("intro\n# Title\n## Sub `x`\n#### Deep\ntext"));
        }

        [Fact]
        public void Paragraph_lines_are_kept_as_line_breaks_and_crlf_is_normalized()
        {
            Assert.Equal("<p>one<br>two</p><p>three</p>", Render("one\r\ntwo\r\n\r\nthree"));
        }
    }
}
